version: '3.4'
services:
    node:
        build: 
            context: ./
            dockerfile: ./.devcontainer/dockerfile
        env_file: .env
        volumes:
            - ./:/usr/src/${APPNAME:-app}
            - config:/root
            - node_modules:/usr/src/${APPNAME:-app}/node_modules
        tty: true
        working_dir: /usr/src/${APPNAME:-app}
        ports:
            - '8080:5000'
            - "35729:35729"
        entrypoint: ["/bin/sh"]
        environment:
            - CHOKIDAR_USEPOLLING=true
            - HOST=0.0.0.0
volumes:
    node_modules:
        driver: local
    config:
        driver: local
    
    
